### ISSUE TITLE
Could not find function locate_credentials()

### ISSUE THREAD

**Issue by dkincaid** [cloudyr/aws.polly#3]
Installed the package from Github using `devtools::install_github("cloudyr/aws.polly")`. Then ran the following example from the README:

```R
> library("aws.polly")
> vec <- synthesize("Hello world!", voice = "Joanna")
```
and get the following error:

```
Error in locate_credentials(key = key, secret = secret, session_token = session_token,  : 
  could not find function "locate_credentials"
```

if I manually load the aws.signature package using `library("aws.signature")` then it works.

**Comment by leeper** [comment]
Oops, sorry about that. Please reinstall from GitHub.

**Comment by dkincaid** [comment]
Dang! That was a fast fix! Thanks. This is the coolest thing I've seen in a while!
