### ISSUE TITLE
Seeking new maintainer!

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.polly#4]
This package is not being actively maintained. If you're interested in contributing or taking over, please express your interest here.

**Comment by antoine-sachet** [comment]
I have already taken over `aws.comprehend` and I am happy to start maintaining `aws.polly` and `aws.transcribe` since I use both.

@MarkEdmondson1234

**Comment by MarkEdmondson1234** [comment]
Thanks!  Have created an aws language group, and added you as a member - this holds aws.transcribe, aws.polly and aws.comprehend.
